#pragma once

//#define IMAGE_FILE_NAME_OFFSET 0x460
#define _EPROCESS_IMAGE_FILE_NAME_OFFSET		0x468

#define _EPROCESS_WIN32_PROCESS_OFFSET			0x3a8

#define _EPROCESS_ACTIVE_PROCESS_LINKS_OFFSET	0x2e8